# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-22 20:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('image', models.ImageField(upload_to='img/')),
                ('name', models.CharField(choices=[('Beauty_and_Health', 'Beauty and Health'), ('Clothing', 'Clothing'), ('Electronics', 'Electronics'), ('Food_and_Drinks', 'Food and Drinks'), ('Grocery', 'Grocery'), ('Home', 'Home')], max_length=30)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='img/')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=2000)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vip.Category')),
                ('store', models.ManyToManyField(to='vendor.Store')),
            ],
        ),
    ]
