# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vip', '0003_auto_20170725_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Beauty and Health', 'Beauty and Health'), ('Clothing', 'Clothing'), ('Electronics', 'Electronics'), ('Food and Drinks', 'Food and Drinks'), ('Grocery', 'Grocery'), ('Home', 'Home')], max_length=30),
        ),
    ]
