# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-31 20:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('valet', '0002_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequence',
            name='driver',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='valet.Driver'),
        ),
    ]
