# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-01 23:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('valet', '0004_auto_20170801_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumerSequence',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('seq', models.CharField(max_length=200)),
                ('driver', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='valet.Driver')),
            ],
        ),
    ]
