# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-22 20:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sign_up', '0001_initial'),
        ('vip', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now=True)),
                ('consumer', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='sign_up.Consumer')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=2000)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cart.Cart')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vip.Item')),
            ],
        ),
    ]
