# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-31 16:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vip', '0003_auto_20170725_1238'),
        ('sign_up', '0002_auto_20170724_1258'),
        ('cart', '0003_order_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='item',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
        migrations.AddField(
            model_name='order',
            name='consumer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sign_up.Consumer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='delievered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='item',
            field=models.ManyToManyField(to='vip.Item'),
        ),
        migrations.AddField(
            model_name='order',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='valet.Driver'),
        ),
    ]
