# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-01 20:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_auto_20170731_1249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delievered',
            new_name='delivered',
        ),
    ]
